language: go
sudo: false
go:
  - 1.x
  - master
before_install:
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
script:
  - go test ./...
  - go test -c -covermode=count -coverpkg=github.com/hexdigest/gotests,github.com/hexdigest/gotests/internal/input,github.com/hexdigest/gotests/internal/render,github.com/hexdigest/gotests/internal/goparser,github.com/hexdigest/gotests/internal/output,github.com/hexdigest/gotests/internal/models
  - ./gotests.test -test.coverprofile coverage.cov
  - $HOME/gopath/bin/goveralls -service=travis-ci -coverprofile=coverage.cov
